# Generated by Django 5.2.13 on 2026-09-24 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payment_method_payment_status_and_more'),
        ('projects', '0005_comment_client_job_reaction_client_job_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorPayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('project_title', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_method', models.CharField(choices=[('upi', 'UPI Transfer'), ('bank', 'Bank Transfer (NEFT/IMPS)')], default='upi', max_length=20)),
                ('recipient_detail', models.CharField(help_text='Snapshot of the UPI ID or masked bank account used at time of payout', max_length=255)),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('processing', 'Processing'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payouts', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_payouts', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_payouts', to='projects.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerPayoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('preferred_method', models.CharField(choices=[('upi', 'UPI / Virtual Payment Address'), ('bank', 'Bank Account (NEFT / IMPS)')], default='upi', max_length=20)),
                ('upi_id', models.CharField(blank=True, help_text='e.g. name@okhdfcbank', max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=25, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
