# Generated by Django 5.2.13 on 2026-09-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='proposals.proposal'),
        ),
    ]
