# Generated by Django 5.2.13 on 2026-09-20 13:46

import django.core.files.storage
import freelancer_portal.upload_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clientprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='banner_image',
            field=freelancer_portal.upload_utils.SafeImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/Users/apple/projects/main_project/freelancer_portal'), upload_to=freelancer_portal.upload_utils.client_banner_path),
        ),
    ]
