# Generated by Django 5.2.13 on 2026-09-18 11:12

import django.core.files.storage
import freelancer_portal.upload_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment_parent_commentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='poster',
            field=freelancer_portal.upload_utils.SafeImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/Users/apple/projects/main_project/freelancer_portal'), upload_to=freelancer_portal.upload_utils.client_poster_path),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='poster',
            field=freelancer_portal.upload_utils.SafeImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/Users/apple/projects/main_project/freelancer_portal'), upload_to=freelancer_portal.upload_utils.freelancer_poster_path),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=freelancer_portal.upload_utils.SafeImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/Users/apple/projects/main_project/freelancer_portal'), upload_to=freelancer_portal.upload_utils.client_job_path),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='image',
            field=freelancer_portal.upload_utils.SafeImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/Users/apple/projects/main_project/freelancer_portal'), upload_to=freelancer_portal.upload_utils.freelancer_talent_path),
        ),
    ]
