# Generated by Django 5.2.13 on 2026-09-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_job_poster_jobpost_poster_alter_job_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='client_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.job'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='client_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='projects.job'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.jobpost'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='projects.jobpost'),
        ),
    ]
