# Generated by Django 5.2.13 on 2026-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_comment_client_job_reaction_client_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when the client accepted a freelancer's bid.", null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expected_completion_date',
            field=models.DateTimeField(blank=True, help_text="Target completion date based on accepted bid's delivery days.", null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this project can receive bids and appears in active listings.'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='open', max_length=20),
        ),
    ]
