# Generated by Django 5.2.13 on 2026-09-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_connected_at_connection_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
