# Generated by Django 5.2.13 on 2026-09-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='available_connects',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='used_connects',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='available_connects',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='user',
            name='used_connects',
            field=models.IntegerField(default=20),
        ),
    ]
