# Generated by Django 5.2.13 on 2026-09-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_testimonial_available_connects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('proposal_view', 'Proposal View'), ('proposal_status', 'Proposal Status'), ('new_project', 'New Project'), ('message', 'Message'), ('system', 'System'), ('connection_request', 'Connection Request')], max_length=20),
        ),
    ]
