# Generated by Django 5.2.13 on 2026-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the bid was accepted by the client.', null=True),
        ),
    ]
