# Generated by Django 5.2.13 on 2026-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_freelancerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
