# Generated by Django 5.2.13 on 2026-09-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
