# Generated by Django 5.2.13 on 2026-09-18 11:12

import django.core.files.storage
import freelancer_portal.upload_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_alter_freelancerprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='profile_picture',
            field=freelancer_portal.upload_utils.SafeImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/Users/apple/projects/main_project/freelancer_portal'), upload_to=freelancer_portal.upload_utils.freelancer_profile_path),
        ),
    ]
